version: "3.4"

services:
  fiaphaka-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: FiapHaka123
    ports:
      - "1433:1433"
    networks:
      - my-network

  fiaphaka-back:
    image: fiaphaka-back
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - fiaphaka-db
    networks:
      - my-network
    #tty: true

#   fiaphaka-front:
#     image: fiaphaka-front
#     build:
#       context: ../fiaphaka-front/
#       dockerfile: Dockerfile
#     environment:
#       TZ: America/Sao_Paulo
#       ASPNETCORE_ENVIRONMENT: Production
#     ports:
#       - 5173:5173
#     networks:
#       - my-network

networks:
  my-network:
    driver: bridge
