# Necessário subir a IMAGE para o DockerHub para funcionar, porém gratuitamente só é possível subir 1 (alterar linha 20 com a imagem cloud);

#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiaphakadeployback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiaphakapod
  template:
    metadata:
      labels:
        app: fiaphakapod
    spec:
      containers:
        - name: fiaphakapod
          image: fiaphaka-back:latest
          ports:
            - containerPort: 8080
---
#LoadBalance
apiVersion: v1
kind: Service
metadata:
  name: fiaphakalbback
spec:
  selector:
    app: fiaphakapod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
