#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiaphakadeployfront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiaphakapod
  template:
    metadata:
      labels:
        app: fiaphakapod
    spec:
      containers:
        - name: fiaphakapod
          image: fiaphaka-front:latest
          ports:
            - containerPort: 80
---
#LoadBalance
apiVersion: v1
kind: Service
metadata:
  name: fiaphakalbfront
spec:
  selector:
    app: fiaphakapod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
