name: build-and-deploy-production

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login into Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      #gmtpostechacr.azurecr.io
      - name: Build the Docker image
        run: docker build -t ${{ secrets.PROJECT_NAME }}:${{ github.sha }} .

      - name: Tag Docker Image
        run: docker tag ${{ secrets.PROJECT_NAME }}:${{ github.sha }} ${{ secrets.AZURE_ACR_SERVER }}/${{ secrets.PROJECT_NAME }}:${{ github.sha }}

      - name: Push Docker to Azure Container Registry
        run: docker push ${{ secrets.AZURE_ACR_SERVER }}/${{ secrets.PROJECT_NAME }}:${{ github.sha }}

  push-to-aci:
    needs: build-and-push-acr
    runs-on: ubuntu-latest

    steps:
      - name: Login into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.AZURE_RESOURCEGROUP }}
          name: ${{ secrets.AZURE_ACI_NAME }}
          image: ${{ secrets.AZURE_ACR_SERVER }}/${{ secrets.PROJECT_NAME }}:${{ github.sha }}
          registry-username: ${{ secrets.AZURE_ACR_USERNAME }}
          registry-password: ${{ secrets.AZURE_ACR_PASSWORD }}
          dns-name-label: ${{ secrets.AZURE_RESOURCEGROUP }}${{ github.run_number }}
          location: "brazilsouth"
